#!/bin/bash

#Asking the user to enter the workspace directory for colmap
read -e -p "Enter of the workspace for 3D reconstruction: " workdir

#Assuming that the directory is structured as per colmap, selecting the image directory
imagedir="${workdir}images"

#Initiating automatic reconstriuction colmap (sparse reconstruction)
colmap automatic_reconstructor --workspace_path $workdir --image_path $imagedir --data_type video --quality medium --sparse 1 --dense 0

#Creating a directoy to store ground segmented images
mkdir -p $workdir/ground_segmented_images

#Segmenting the images to identify ground plane
conda activate IIITH
python ~/Github/autonomous-delivery-robot/semantic_segmentation/test_single_image.py -i $imagedir -o $workdir/ground_segmented_images 

#Finding the ground normal from the segmented images and the text files generated by colmap
colmap model_converter --input_path "${workdir}sparse/0/" --output_path "${workdir}/sparse/0/" --output_type TXT
# imagestxt = "${workdir}/sparse/0/images.txt"
# points3dtxt = "${workdir}/sparse/0/points3D.txt"
# segmented = "${workdir}/ground_segmented_images/"
conda activate RL
python ~/Github/Drone-based-building-assessment/distance_between_adjBuildings/ground_normal.py -i "${workdir}/sparse/0/images.txt" -p "${workdir}/sparse/0/points3D.txt" -s "${workdir}/ground_segmented_images/"